server:
  port : 8080
  servlet:
    context-path: /capitole

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect 
  application:
    moduleid: capitole
    name: capitole
  cloud:
    config:
      enabled: false
  sleuth:
    baggage:
      correlation-fields:
        - c4-traceId
      remote-fields:
        - c4-traceId

springdoc:
  packagesToScan: com.prueba.capitole.infrastructure.controller
  title: capitole
  description: capitole

aspect:
  logging:
    enabled: true
    logParameters: true
    logRequest: true
    logResponse: true